nodes:
  controller-0:
    name: controller-0
    personality: controller
    bmc_ip:
    bmc_user: usr
    bmc_pswd: pswd
    pxe_nic_mac:
    installation_ip:
    oam_if:
    mgmt_if:
  controller-1:
    name: controller-1
    personality: controller
    bmc_ip:
    bmc_user: usr
    bmc_pswd: pswd
    pxe_nic_mac:
  compute-0:
    name: compute-0
    personality: worker
    bmc_ip:
    bmc_user: usr
    bmc_pswd: pswd
    pxe_nic_mac:
  compute-1:
    name: compute-1
    personality: worker
    bmc_ip:
    bmc_user: usr
    bmc_pswd: pswd
    pxe_nic_mac:
